Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
nb = MultinomialNB()
nb.fit(X_train_pca, y_train)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_pca, y_train)

------------------

[0;31m[0m
[0;31mValueError[0mTraceback (most recent call last)
[0;32m<ipython-input-5-948a3ee6cb16>[0m in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [0mnb[0m [0;34m=[0m [0mMultinomialNB[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mnb[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0mX_train_pca[0m[0;34m,[0m [0my_train[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mknn[0m [0;34m=[0m [0mKNeighborsClassifier[0m[0;34m([0m[0mn_neighbors[0m[0;34m=[0m[0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mknn[0m[0;34m.[0m[0mfit[0m[0;34m([0m[0mX_train_pca[0m[0;34m,[0m [0my_train[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py[0m in [0;36mfit[0;34m(self, X, y, sample_weight)[0m
[1;32m    774[0m         [0mn_classes[0m [0;34m=[0m [0mY[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    775[0m         [0mself[0m[0;34m.[0m[0m_init_counters[0m[0;34m([0m[0mn_classes[0m[0;34m,[0m [0mn_features[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 776[0;31m         [0mself[0m[0;34m.[0m[0m_count[0m[0;34m([0m[0mX[0m[0;34m,[0m [0mY[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    777[0m         [0malpha[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_check_alpha[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    778[0m         [0mself[0m[0;34m.[0m[0m_update_feature_log_prob[0m[0;34m([0m[0malpha[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py[0m in [0;36m_count[0;34m(self, X, Y)[0m
[1;32m    896[0m     [0;32mdef[0m [0m_count[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mX[0m[0;34m,[0m [0mY[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    897[0m         [0;34m"""Count and smooth feature occurrences."""[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 898[0;31m         [0mcheck_non_negative[0m[0;34m([0m[0mX[0m[0;34m,[0m [0;34m"MultinomialNB (input X)"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    899[0m         [0mself[0m[0;34m.[0m[0mfeature_count_[0m [0;34m+=[0m [0msafe_sparse_dot[0m[0;34m([0m[0mY[0m[0;34m.[0m[0mT[0m[0;34m,[0m [0mX[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    900[0m         [0mself[0m[0;34m.[0m[0mclass_count_[0m [0;34m+=[0m [0mY[0m[0;34m.[0m[0msum[0m[0;34m([0m[0maxis[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py[0m in [0;36mcheck_non_negative[0;34m(X, whom)[0m
[1;32m   1416[0m [0;34m[0m[0m
[1;32m   1417[0m     [0;32mif[0m [0mX_min[0m [0;34m<[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1418[0;31m         [0;32mraise[0m [0mValueError[0m[0;34m([0m[0;34m"Negative values in data passed to %s"[0m [0;34m%[0m [0mwhom[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1419[0m [0;34m[0m[0m
[1;32m   1420[0m [0;34m[0m[0m

[0;31mValueError[0m: Negative values in data passed to MultinomialNB (input X)
ValueError: Negative values in data passed to MultinomialNB (input X)

